version: '3.8'

services:
  blockscout:
    image: ecoblocklabs/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        DISABLE_READ_API: "false"
        API_PATH: "/"
        NETWORK_PATH: "/"
        DISABLE_WEBAPP: "false"
        DISABLE_WRITE_API: "false"
        CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        SOCKET_ROOT: "/"
        WOBSERVER_ENABLED: "false"
        ADMIN_PANEL_ENABLED: ""
    restart: always
    container_name: 'blockscout'
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    env_file:
      - ./envs/common-blockscout.env
    ports:
      - "4000:4000"
    volumes:
      - ./logs/:/app/logs/

